version: "3.7"

services:
    refactorv2:
        build:
            context: .
            dockerfile: dockerfile
        image: refactorv2
        container_name: refactorv2
        networks:
            - network
        ports:
            - 88:80

networks:
    network:

volumes:
    mssql: